# -*- coding: utf-8 -*-
"""sheet 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I5nnSnS34mKBKdSveXwyRq4KFn1ExYh6

##Question 1:
Write a python program to input an alphabet and check whether it is
vowel or consonant.
 
Note: Vowel alphabets are: {a, e, o, u, i}
All other alphabets are consonant
"""

x=("a","e","o","u","i")
vowel = input("please enter letter")
if vowel.lower() in x:
  print(vowel,"is vowel")
else:
 print(vowel,"is constant")

"""##Question 2:
Write a python program that prompts the user to input a number. The
program should then output this number and a message saying whether
it is even or odd.
"""

num = int(input("please enter letter"))
print(num," is Even") if num%2==0  else print(num," is odd")

"""##Question 3:
Write a python program to input a character from user and check whether
the given character is alphabet, digit or special character.
"""

Enter = input("please enter any character:")
if Enter.isalpha () :
    print(Enter,"  it is alphabet")
elif Enter.isdigit():
    print(Enter," it is Digit")
else:
    print(Enter," it is special character")

"""##Question 4:
Write a python program that prompts the user to input a number. The
program should then output this number and a message saying whether it
is positive, negative, or zero. Question 5:
"""

num = int(input("please enter letter"))
print(num," is postive") if num>=0  else print(num," is Negative")

"""##Question 5:
Write a python program of a four-function calculator. The program
should ask the user to enter a number, an operator, and another number. It
should then carry out the specified arithmetical operation:
"""

while True:
  operator=("+","-","/","*")
  num_1 = int(input("please enter number"))
  num_2 = int(input("please enter number"))
  operator_1 = input("please enter operator")
  if operator_1 =="+":
      print(num_1+num_2)
  elif operator_1 =="-":
      print(num_1-num_2)
  elif operator_1 =="*":
      print(num_1*num_2)
  elif operator_1 =="/":
       if num_2!=0:
         print(num_1/num_2)
       else:
         print("ZeroDivisionError")
  else:
     print('error')  

  c=input("do you want continue ?" "yes" "no")
  if c.lower()=="no":
         break;

"""##Question 6:
Write a python program that will prompt the user to input 5 integer values
to be stored in a list. 
"""

x=[]
for i in range(0,5):
  number =int(input("please enter five numbers"))
  x.append(number)
print(x)

"""## Question 7:
Write a python program that print the values of a list.
"""

lst_x=[9,8,7,6,8,3]
for i in lst_x:
  print(i, end =" ")

"""##Question 8:
Write a python program that print the values of a list in a reverse order.
"""

lst_y=[1,2,5,7,9,7]
print(lst_y[::-1])

lst_y=[1,2,5,7,9,7]
for i in range(len(lst_y)-1,-1,-1):
   print(lst_y[i],end="  ")

"""##Question 9:
Write a python program that will prompt the user to input a list of 5
integer values. Then it print their summation and average. 
"""

sum=0
for i in range (5):
  i=+1
  num_1 = int(input("please enter your numbers"))
  sum+=num_1
print("the sum for the numbers is ", sum , "the average for the number is ", sum/num_1)

sum=0
x=0
while x<=4:
   x+=1
   num = int(input("please enter your numbers"))
   sum+=num
print("the sum for the numbers is ", sum , "the average for the number is ", sum/x)

"""1## Question 10:
Write a python program that will prompt the user to input a list of 5
integer values. Then it print the summation and average of its contained
even numbers.
"""

even=[]
sum=0
x=0
while x<=4:
   x+=1
   num = int(input("please enter your numbers"))
   sum+=num
   if num%2==0:
     even.append(num)
print("the sum for the numbers is ", sum , "the average for the number is ", sum/x,"even numbers are ",even)

"""##Question 11:
Write a python program that will prompt the user to input a list of 5
integer values. Then it print its maximum and minimum values.
"""

lst_4=[]
for i in range(0,5):
  num_1 =int(input("please enter your numbers"))
  lst_4.append(num_1)
print(max(lst_4),"is your max number")
print(min(lst_4),"is your min number")

"""## Question 12:

Write a python program that will prompt the user to input a list of 5
integer values. Then it ask the user to enter a number to check whether or
not this number is found in the list or not.
"""

lst_3=[]
for i in range(0,5):
  num_1 =int(input("please enter your numbers"))
  lst_3.append(num_1)
num_2=int(input("please enter your numbers"))
if num_2 in lst_3:
   print("your number is exist")
else :
   print(num_2," your number is not exist")

"""##Question 13:
Write a python program that will prompt the user to input an index of a
list to print its value.
"""

lst_6=[0,"fgj",9,"","78"]
index= int(input("please inter index:"))
print("your value number is :",lst_6[index])
  # not working with error

"""Question 14:
Write a python program that will prompt the user to input a list of 5
integer values. Then it count the number of occurrence of the given
number in such list.
"""

n=[]
a={}
for i in range(5):
  num_1 =int(input("please enter your numbers")) 
  n.append(num_1)
print('numbers of the users',n)
for j in n:
  if j in a:
    a[j]+=1
  else:
    a[j]=1
print("count occurance for each number:",a)

8754s=[]
count=0
for i in range(5):
  num_1 =int(input("please enter your numbers")) 
  s.append(num_1)
  x=s.count(num_1)
print("th occurance of given number are",x)

"""##Question 15:
7Write a python program that will prompt the user to input a list of 5
integer values. Then it splits the list into two lists; the first will contains
even numbers while the other will contain odd numbers.
"""

lst_1=[]
lst_2=[]
num_1, num_2,num_3 = map(int, input("please enter 3 numbers").split(","))
num_4, num_5,num_6 = map(int, input("please enter 3 numbers").split(","))
lst_1.append ([num_1,num_2,num_3])
lst_2.append([num_4, num_5,num_6])
lst3 = lst_1+lst_2
print(lst3)

lst_5=["cake","bread","milk","meat"]
lst_6=[1,2,3,4,5,6]
lst_7=lst_5+lst_6 
print(lst_7)

"""##Question 16:
Write a python program that will prompt the user to input a list of 5
integer values. Then it splits the list into two lists; the first will contains
even numbers while the other will contain odd numbers.
"""

even=[]
odd=[]
for i in range(5):
 num=int(input("please enter your numbers"))
 if num%2==0: 
    even.append(num)
 else:
    odd.append(num)
print(f"the even numbers are {even}")
print(f"the odd numbers are {odd} ")

"""##Question 17:
Write a python program that asks the user to enter an integer number then
it prints its factorial
Note: factorial(n) = n*(n-1)*(n-2)*(n-3)*(n-4).......*3*2*1
"""

a=int(input("please enter your numbers"))
fact=1
if a <0: print("invalid input")
elif a==0:print(fact)
else:
 for i in range (a,1,-1):
   fact*=i
 print(fact,"is your factorial number")

"""##Question 18:
Write a python program that asks the user to enter two integer numbers, a
and b, then it prints a power b
Note: a power b= a *a *a .... ( b times)
"""

a=int(input("please enter your numbers"))
b=int(input("please enter your numbers"))
counter=0
result=1
while counter < b:
  result*=a
  counter+=1
print(result)