# -*- coding: utf-8 -*-
"""sheet 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GLNj8d4A-1Q-ggNcRxuL8dolLLJnV35y

Question 1:
Write a python Function to input an alphabet and check whether it is
vowel or consonant. Note: Vowel alphabets are: {a, e, o, u, i}
All other alphabets are consonant
"""

def vowel ():
 vowel =("a", "e", "o", "u", "i")
 letter= input(" please enter your letter")
 if letter.lower() in vowel :
  print(letter," this letter is  vowel")
 else:
   print(letter," this letter is constant")

vowel()

"""Question 2:
Write a function that prompts the user to input a number. The
program should then output this number and a message saying whether
it is even or odd. 
"""

def even_odd():
 number= int(input("please enter your number"))
 if number%2==0:
  print(number, "this number is even")
 else:
  print(number, "this number is odd")

even_odd()

"""Question 3:
Write a function to input a character from user and check whether
the given character is alphabet, digit or special character. 
"""

def alphabet_digit_specialcharacter():

  enter= input("please enter alphabet or digit or special character")
  if enter.isdigit() :
    print(f"{enter},is digit number")
  elif enter.isalpha():
    print(f"{enter},is alphabet")
  else:
    print(enter,"is special charachter")

alphabet_digit_specialcharacter()

"""Question 4:
Write a python program that prompts the user to input a number. The
program should then output this number and a message saying whether it
is positive, negative, or zero.
"""

def positive_negative_zero():
  num= int(input("please enter the number"))
  if num<0:
     print(f"{num},the number is negative")
  elif num>0:
     print(f"{num},the number is positive")  
  else:  
     print(f"{num},the number is zero")

positive_negative_zero()

"""Question5: Write a Function of a four-function calculator. The program
should ask the user to enter a number, an operator, and another number. It
should then carry out the specified arithmetical operation:
"""

def operation():
 while True :
  operator=("+","-","*","/")
  operation= input(" please enter the operation")
  num_1=int(input("please enter your first number"))
  num_2= int(input("please enter your seconed number"))
  if operation=="+":
   print(f"the total number is ,{num_1+num_2}")
  elif operation=="-":
   print(f"the total number is ,{num_1-num_2}")
  elif operation=="*":
   print(f"the total number is ,{num_1*num_2}")
  elif operation=="/":
    if num_2!=0:
     print(f"the total number is ,{num_1/num_2}")
    else:
     print("ZeroDivisionError")
  else:
    print("error")    
  c=input("please do you want to continue,yes or no ?")
  if c.lower()== "no":
      break;

operation()

"""Question6 : Write a function that reads a file and print the number of plandromic words that it
contains.
"""

def plandromic_words():
 with open("Alaa.txt","r",encoding="utf-8") as file :
   lines= file.readlines()
   for line in lines :
    words=line.strip().split(" ")
    for word in words:
       word.strip().split(" ")
       if word==word[::-1] :
         print(word," this word is plandromic ")

plandromic_words()

"""Question 7: Write a function that prompts the user to enter a text filename and displays the
number of vowels and consonants in the file.
"""

def vowel():
  file_name= input("please enter yor file name")
  with open (file_name,"r",encoding="UTF-8") as file:
   vowels = set("A E I O U a e i o u")
   constant = set("b c d f g h j k l m n p q r s t v w x y z B C D F G H J K L M N P Q R S T V W X Y Z")
   count_v=0
   count_constant=0
   lines=file.readlines()
   for line in lines:
     words= line.strip().split(" ")
     no_of_words=len(words)
     for word in words:
       letters= word.strip().split(" ")
       no_of_letters=len(letters) 
       for letter in word :
          if letter in vowels:
            count_v+=1
          else:
           count_constant+=1
   print("number of vowels is",count_v,"number of constant",count_constant)

vowel()